### ISSUE TITLE
Yoooooo

### ISSUE THREAD

**Issue by zqpvr** [topitbopit/Redline#1]
This is awesome can you add fly bypasses as well also I am now gonna use this cause the velocity limiter for my netless script that's private and so I don't get flung by skids in games dope man. also check the game isle on roblox out try to get bypasses for that I bypassed anti tp sorta and cframe bypasses there anticheat for speed and try to get a anti tp bypass that works for most games thanks

**Comment by topitbopit** [comment]
Thanks
I'll let you know when i add more bypass modes, rn im just working on finishing all the other modules

**Comment by zqpvr** [comment]
yup just tested a few days ago a few features work currently it would be good to see it complete soon as it is in beta looking forward to seeing you update the script my jailbreak tp also works but that's on my other computer and the fly with the tp both work perfectly I don't get teleported back most times edit:(you should also throw an image of redlines UI in roblox onto the github)
